name: CI Imitation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml up --build --exit-code-from tests
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: ./app
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: netology-code/ib-devsecops-app/devsecops-app
          tag_with_ref: true
